# -*- coding: utf-8 -*-
"""Virtual_Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RcCDJ_XZjjXXCPYn6eRXdd1eY0VdOlmn
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    try:
        return x / y
    except ZeroDivisionError:
      return "Error: Division by Zero"



def calculator():
    print("Simple Virtual Calculator")
    print("Operations: +, -, *, /")

    while True:
      try:
        num1 = float(input("Enter the first number: "))
        operator = input("Enter the operator (+, -, *, /): ")
        num2 = float(input("Enter the second number: "))

        if operator == '+':
            result = add(num1, num2)
        elif operator == '-':
            result = subtract(num1, num2)
        elif operator == '*':
            result = multiply(num1, num2)
        elif operator == '/':
            result = divide(num1, num2)
        else:
            print("Invalid operator. Please try again.")
            continue

        print("Result:", result)

        choice = input("Do you want to perform another calculation? (y/n): ")
        if choice.lower() != 'y':
            break

      except ValueError:
        print("Invalid Input and Please enter a valid number")
      except Exception as e:
        print("An error occurred:", e)

#main program
calculator()